spring.datasource.url=jdbc:postgresql://localhost:5442/banjock_db
server.port= 8090
spring.datasource.username=bude
spring.datasource.password=bude

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
